dev-dependencies = { }
dev-addresses = { }

[package]
name = "PropsharkContracts"
edition = "2024.beta"
published-at = "0xea29c5548d3d8b8de743aa8166a78ed473ae7a2e348882129a7656869a2c7ef8"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/testnet"

[dependencies.DeepBook]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/deepbook"
rev = "framework/testnet"

[dependencies.SuiTears]
local = "../suitears/contracts"

[addresses]
propshark_contracts = "0xea29c5548d3d8b8de743aa8166a78ed473ae7a2e348882129a7656869a2c7ef8"
deepbook = "0xdee9"
suitears = "0xfe96bb1a6fc447e83e5c9d741bf8565f619d099bff6e540bcc95d487c4f47683"
