dev-dependencies = { }
dev-addresses = { }

[package]
name = "house_three"
edition = "2024.beta"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/testnet"

[dependencies.PropsharkContracts]
local = "../../propshark-contracts"

[dependencies.SuiTears]
local = "../../suitears/contracts"

[addresses]
house_three = "0x0"
propshark_contracts = "0xea29c5548d3d8b8de743aa8166a78ed473ae7a2e348882129a7656869a2c7ef8"
suitears = "0xfe96bb1a6fc447e83e5c9d741bf8565f619d099bff6e540bcc95d487c4f47683"
